// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-wKzGOLOaq_SmFermeWim39ma9v7AVh4',
    appId: '1:554584170393:web:6d8aa0b894ef3c7e61bd08',
    messagingSenderId: '554584170393',
    projectId: 'db-yourop',
    authDomain: 'db-yourop.firebaseapp.com',
    databaseURL: "https://db-yourop-default-rtdb.firebaseio.com",
    storageBucket: 'db-yourop.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP6xGU70w8S98jQ3KF_ljQ9zMM_xeoB2M',
    appId: '1:554584170393:android:998e70ec7089fb6e61bd08',
    messagingSenderId: '554584170393',
    databaseURL: "https://db-yourop-default-rtdb.firebaseio.com",
    projectId: 'db-yourop',
    storageBucket: 'db-yourop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMAu_qnb6UHgwDZK8DeXygc61PtQUjKyk',
    appId: '1:554584170393:ios:2c06523ba5a7899361bd08',
    messagingSenderId: '554584170393',
    projectId: 'db-yourop',
    storageBucket: 'db-yourop.appspot.com',
    iosClientId:
        '554584170393-slfordjbff6opgrbdjon0g1glhvr8ub3.apps.googleusercontent.com',
    iosBundleId: 'com.example.yourop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMAu_qnb6UHgwDZK8DeXygc61PtQUjKyk',
    appId: '1:554584170393:ios:b80eea3fb6ae8afb61bd08',
    messagingSenderId: '554584170393',
    projectId: 'db-yourop',
    storageBucket: 'db-yourop.appspot.com',
    iosClientId:
        '554584170393-jqmepvmq03d54voq2a097n9ut8tunqaa.apps.googleusercontent.com',
    iosBundleId: 'com.example.yourop.RunnerTests',
  );
}
